
# A list of devices you want to take the screenshots from
 devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
   "iPad Retina",
   "iPad Pro"
 ])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "build_scheme_string"

clear_previous_screenshots true

number_of_retries 10

skip_open_summary true
